pipeline{
    agent any
    environment{
        IMAGE_NAME = "amitmkhavatgoppa/devops-masterclass:${GIT_COMMIT}"
    }
    stages{
        stage('git-checkout'){
            steps{
                git url: 'https://github.com/Amitm19/devops-masterclass.git', branch: 'main'
            }
        }
        stage('build'){
            steps{
                sh '''
                    printenv
                    docker build -t ${IMAGE_NAME} .
                '''
            }
        }
    }
}